### ISSUE TITLE
🐞 Dagger doesn't respect SIGINT (ctrl-c)

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#4823]
### What is the issue?

From @RonanQuigley
> Dagger does not respect SIGINT (ctrl + c). Able to replicate on Mac and Linux.

> We would request prioritising getting the SIGINT issue fixed ASAP. We found that it's a productivity killer (we made a lot of mistakes when making our pipelines, and having to kill the process manually each time gets tedious very quickly).

### Log output

n/a

### Steps to reproduce

run a pipeline and hit ctrl-c. It seems like SIGINT is ignored while the Dagger pipeline is running.

### SDK version

Node.js SDK

### OS version

mac, linux

**Comment by kpenfound** [comment]
@jpadams it seems like maybe this is specific to nodejs. We may just need to document the best practices for async processes in nodejs and how to handle process signals

**Comment by RonanQuigley** [comment]
Here's a code snippet to reproduce. Replicated with Dagger 0.4.2. 

```
import * as dagger from '@dagger.io/dagger';

dagger.connect(
  async (client) => {
    await client.container().from('node').withExec(['']).stdout();
  },
  {
    LogOutput: process.stdout,
    Workdir: '.',
  }
);
```

You'll need to handle the graceful shutdown with `process.on('SIGINT')`. When running in k8s, you need `process.on('SIGTERM')`

**Comment by slumbering** [comment]
Thanks @RonanQuigley for this reporting. 
I've just opened a PR that should fix the issue: 
- #4911

**Comment by kpenfound** [comment]
This still appears to be an issue with the latest nodejs sdk.

To reproduce, run the github.com/dagger/examples/nodejs/react-build/build.js pipeline (update to latest sdk first). Once it starts running, ctrl+c. It'll keep running until it's done

**Comment by slumbering** [comment]
> SIGINT



> This still appears to be an issue with the latest nodejs sdk.
> 
> To reproduce, run the github.com/dagger/examples/nodejs/react-build/build.js pipeline (update to latest sdk first). Once it starts running, ctrl+c. It'll keep running until it's done

Ok. Thanks @kpenfound for the heads-up. I'll tackle this one as soon as I can.

**Comment by grouville** [comment]
> This still appears to be an issue with the latest nodejs sdk.
> 
> To reproduce, run the github.com/dagger/examples/nodejs/react-build/build.js pipeline (update to latest sdk first). Once it starts running, ctrl+c. It'll keep running until it's done

I have tried with the latest version of the SDK [0.6.0](https://www.npmjs.com/package/@dagger.io/dagger) and it seems to work 100% fine on my side

**Comment by gerhard** [comment]
@grouville care to share a recording of how you confirmed the correct behaviour? Use whichever is easiest:
- https://asciinema.org/ + https://lib.rs/crates/asciinema-scenario
- https://github.com/saschagrunert/demo
- https://www.loom.com/

**Comment by grouville** [comment]
> @grouville care to share a recording of how you confirmed the correct behaviour? Use whichever is easiest:
> 
> * https://asciinema.org/ + https://lib.rs/crates/asciinema-scenario
> * https://github.com/saschagrunert/demo
> * https://www.loom.com/

sure: https://www.loom.com/share/4919665f9f7e4aa2836b4582af97d54f. 

Here I tested the `build.js` and `build.mts`

**Comment by gerhard** [comment]
That was super helpful - thanks @grouville!

I just confirmed that this was an issue with `@dagger.io/dagger@0.4.2`:

![image](https://github.com/dagger/dagger/assets/3342/6812a753-9cfb-492e-b436-d385e09e25f9)

Fixed in Node.js SDK `v0.6.0` 👍

---

@kpenfound how should we keep the Dagger dependency updated in https://github.com/dagger/examples?
