### ISSUE TITLE
🐞 using HEAD as ref of a git repository

### ISSUE THREAD

**Issue by becojo** [dagger/dagger#7712]
### What is the issue?

When using a git repository URL for a directory argument, Dagger seems to assume that the default branch is named `main`. This is often not the case. 

I also cannot use `HEAD` as ref. You can see in the error message the commit `HEAD` is pointing to but Dagger does not handle it.

When Dagger is provided a Git URL without ref, it should mimic a `git clone` of that URL and not guess the default branch.

### Dagger version

dagger v0.11.6 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

```
dagger call -m github.com/jpadams/semgrep-dagger-module@2d91746e95d15790051f3e3544b51dac84743e4c scan --source https://github.com/JustinCoker991/serverless-plugin-treeshake
Stderr:
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Function execution error: resolve: failed to load cache key: repository does │
│ not contain ref main, output: ""                                             │
╰──────────────────────────────────────────────────────────────────────────────╯
```

```
dagger call -m github.com/jpadams/semgrep-dagger-module@2d91746e95d15790051f3e3544b51dac84743e4c scan --source https://github.com/JustinCoker991/serverless-plugin-treeshake#HEAD
Stderr:
╭─ Error ──────────────────────────────────────────────────────────────────────╮
│ Function execution error: resolve: failed to load cache key: repository does │
│ not contain ref HEAD, output:                                                │
│ "689aa86aff89bf2e0240a12dfeee30481cce8d4b\tHEAD\n"                           │
╰──────────────────────────────────────────────────────────────────────────────╯
```

**Comment by grouville** [comment]
Hi 👋 
This was fixed by @jedevc with https://github.com/dagger/dagger/pull/7688, and shall be available as part of v0.11.8. Thanks for reporting the issue 🙏

**Comment by becojo** [comment]
I updated and still have the same behavior without a ref or using `HEAD` as the ref.

I can see in the debug logs that it is still trying to get the main branch:

![image](https://github.com/dagger/dagger/assets/172889/76f5f100-91cc-4cc4-9423-2a68838e8019)
```
dagger call -m github.com/jpadams/semgrep-dagger-module@2d91746e95d15790051f3e3544b51dac84743e4c scan --source https://github.com/JustinCoker991/serverless-plugin-treeshake
```

**Comment by grouville** [comment]
Getting the same behavior, checking rn 👀

**Comment by helderco** [comment]
Fixed in https://github.com/dagger/dagger/pull/7688
