### ISSUE TITLE
Dagger is slow in large monorepos

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#8499]
# Problem

ref: https://discord.com/channels/707636530424053791/1286344441950375986

When running dagger in a bug monorepo, because of the default SDK `include` and `exclude` patterns in the `initialize` phase, the engine can take quite some time (> 30s) to initialize. 

I think part of this problem is that we're currently being very optimistic in the patterns that we set "just in case" the user decides to use some of his monorepo code into the module. Maybe a different approach here could be so the user has to specifically add  any other paths that they need in case their module requires to import any of the current monorepo packages.

# Solution

Make DX faster in monorepos.

**Comment by marcosnils** [comment]
cc @helderco not sure how relevant this is to SDK coexistence :pray:

**Comment by helderco** [comment]
See:
- https://github.com/dagger/dagger/pull/8501
- https://github.com/dagger/dagger/issues/8496

**Comment by helderco** [comment]
I cover the problem with the default includes from Go in:
- https://github.com/dagger/dagger/issues/8496

But here’s a simple example that’s not related to that. It’s just where you put your `dagger.json` and whether you have the necessary excludes or not.

_(I pruned the cache before each example)_

## Daggerize

First, let’s try daggerizing a repo by leaving `dagger.json` at the repo’s root:

```
❯ cd $(mktemp -d)
❯ git init
❯ mkdir -p wat/.yarn
❯ mkfile 6g wat/.yarn/cache
❯ echo .yarn/ > .gitignore
❯ dagger init --sdk=typescript --source=.dagger --name=foo
❯ lt -a
.
├── .dagger/...
├── .git/...
├── wat
│  └── .yarn
│     └── cache
├── .gitignore
├── dagger.json
└── LICENSE
```

Notice that I put a “monster” file, in a seemingly unrelated directory, and it’s included in the upload from the host because by default, anything inside the module’s directory (aka root directory, i.e., where `dagger.json` is) is included:

<img width="1032" alt="Screenshot 2024-09-20 at 15 46 05" src="https://github.com/user-attachments/assets/3753dd07-32f0-409b-a163-c43383eaf98e">

This causes compounding issues in the pipeline if you have heavy loads, for example when it needs to be copied because of a `withDirectory`:

<img width="1322" alt="Screenshot 2024-09-20 at 15 49 41" src="https://github.com/user-attachments/assets/f762d4db-e171-4cec-9b6e-736904fb788d">

And it even gets re-exported back to the host in the end:

<img width="1644" alt="Screenshot 2024-09-20 at 15 51 20" src="https://github.com/user-attachments/assets/3c6629ec-bc94-40fd-bdfc-c69ca842df5c">


The solution here is to exclude `.yarn/` in `dagger.json` (although remember you’ll still have to suffer through `dagger init` before having the file to change in the first place):

```json
{
  "name": "foo",
  "sdk": "typescript",
  "source": ".dagger",
  "exclude": [
    ".yarn/"
  ]
}
```

Additionally this isn't well documented so a lot of folks don't know about it. It's also added friction to do every time you create a module that uses things like `node_modules`, `.yarn`, or `.venv`.

## Standalone

But this doesn’t happen when `dagger.json` is on its own branch of the file tree, separate from the monster file:

```
❯ cd $(mktemp -d)
❯ git init
❯ mkdir -p wat/.yarn
❯ mkfile 6g wat/.yarn/cache
❯ echo .yarn/ > .gitignore
❯ dagger init --sdk=typescript foo
❯ lt -a
.
├── .git/...
├── foo
│  ├── ...
│  ├── dagger.json
├── wat
│  └── .yarn
│     └── cache
├── .gitignore
└── LICENSE
```

Now the upload is much faster (30 **miliseconds**, instead of 50 seconds) because the monster file wasn’t included:

<img width="1097" alt="Screenshot 2024-09-20 at 16 01 54" src="https://github.com/user-attachments/assets/bd089679-2462-4450-a4eb-6acb52b9c16c">

With minor effects on the rest of the pipeline (there’s other bottlenecks elsewhere):

<img width="1627" alt="Screenshot 2024-09-20 at 16 03 36" src="https://github.com/user-attachments/assets/4fbb4ed1-85fd-44f6-a2a1-9f581f55a088">

So `dagger init` runs much faster, as expected.

> [!note]
> I’m using the TypeScript SDK in these examples even though it’s slower than the Go SDK, because I wanted an SDK without implicit includes, and as a throwback to @drmikecrowe in https://github.com/dagger/dagger/issues/6627#issuecomment-2252356111.

## Leveraging `.gitignore`

But, if you use Yarn, you’re likely to have `.yarn/` already in `.gitignore`. Why not leverage that? That’s what I’m doing in:
- https://github.com/dagger/dagger/pull/8501

Now let’s try to daggerize again, with `.gitignore` files enabled by default (from the above PR):

```
❯ cd $(mktemp -d)
❯ git init
❯ mkdir -p wat/.yarn_cache
❯ mkfile 6g wat/.yarn_cache/_monster
❯ echo .yarn_cache > .gitignore
❯ dagger-dev init --sdk=typescript --source=.dagger --name=foo
❯ lt -a
.
├── .dagger/...
├── .git/...
├── wat
│  └── .yarn
│     └── cache
├── .gitignore
├── dagger.json
└── LICENSE
```

This time everything is still included, but with the extra `.yarn/` exclusion by default, even on `dagger init`:

<img width="1121" alt="Screenshot 2024-09-20 at 16 47 19" src="https://github.com/user-attachments/assets/72336805-bc0f-468c-ad2d-330aee19593d">

So the performance is similar to the standalone example:

<img width="1625" alt="Screenshot 2024-09-20 at 16 50 42" src="https://github.com/user-attachments/assets/55a919ca-604a-4ff0-8933-21330299a88e">

Whe’re talking about a difference of 57s instead of 5m20s in this case (82% faster):

<img width="1632" alt="Screenshot 2024-09-20 at 16 51 33" src="https://github.com/user-attachments/assets/de5922cb-2b00-468c-965b-0a52fb3b53b5">

<img width="1629" alt="Screenshot 2024-09-20 at 16 51 45" src="https://github.com/user-attachments/assets/b717c980-63ce-4156-b8f0-6b9826b3141f">


That's why I think parsing `.gitignore` files by default gives the biggest impact right now, in large monorepos. Consider this also. Even with the Go SDK's default includes, in particular of `vendor/`, even if we have (and we do) a heavy `sdk/php/vendor` directory, it'll be excluded by the `.gitignore`. So even the default includes from Go have a lesser effect with the `.gitignore` handling.

**Comment by wingyplus** [comment]
Question about gitignore way: is it need to parse all gitignore files under nested directory? I ask this because in my monorepo, the ignore files are different content based on the project.

**Comment by wingyplus** [comment]
Btw, i like the gitignore approach. So I can maintain ignore only one instead maintain multiple places. And it is easier to teach my colleague on how to ignore the files.

**Comment by helderco** [comment]
> Question about gitignore way: is it need to parse all gitignore files under nested directory? 

Current implementation is only those between the git root and the module subdir. Not inside it, but perhaps it's good to consider it. 🤔

For example, for a `foo/bar` module, patterns are added in this order (provided the `.gitignore` exists):
- `.gitignore`
- `foo/.gitignore`
- `foo/bar/.gitignore`

> I ask this because in my monorepo, the ignore files are different content based on the project.

Not sure I understand. Can you clarify how it affects you?

**Comment by wingyplus** [comment]
> Not sure I understand. Can you clarify how it affects you?

Sorry, I made it unclear. In my monorepo, the .gitignore on the root repository has a few ignore pattern like:

```
# .gitignore
db_certs
.envrc
```

But in subdirectory, that separate per programming language, it has its own ignore file. And under each directory can have ignore file per library or running service:

```
js/.gitignore # specific under js
elixir/libs/lib_a/.gitignore # ignore specific files under lib_a
elixir/services/service_a/.gitignore # ignore specific files under service_a
...
```

**Comment by drmikecrowe** [comment]
100% agree with @wingyplus -- this is absolutely needed
I'll 100% support `.gitignore` if that's the direct taken

However, should it instead respect `.dockerignore` (and nested ones as well)?  That is, however, its purpose -- identify files/folders that should not be in a container

**Comment by helderco** [comment]
@wingyplus, that's all fine. I'm considering also reading the `.gitignore` files from within the module too, I think it makes sense. Even if you have something in a `.gitignore` that you do need during module load, you’ll be able to negate the same pattern in your `dagger.json` (`!` under `exclude`) to include it.

> However, should it instead respect `.dockerignore` (and nested ones as well)?  That is, however, its purpose -- identify files/folders that should not be in a container

I don’t think so, because they’re distinct use cases. The `.gitignore` is much more useful here as most people won’t have the proper `.dockerignore` ones setup, at least not in a way that makes the most sense for arbitrary Dagger modules. Those files are for tailoring a (usually) specific container image to be published and used in a different way from Dagger.

But we do have local and git remote sources that are interchangeable. So you can `dagger call -m github.com/me/my-module` the same as `dagger call -m ./my-module`. Locally today, there’s a big difference between those two calls because the local copy may have a lot more files being included, if not explicitly excluded in `dagger.json` as well.

So, reading `.gitignore` files is only necessary locally since git already filtered the unwanted files on commit + push, and if Dagger reads the `.gitignore` files locally, you should get a similar result compared to executing from git, instead of seemingly random cache misses and longer upload times.

**Comment by attekei** [comment]
My related comment: https://github.com/dagger/dagger/issues/7043#issuecomment-2376665713

**Comment by hariscodes** [comment]
This might be unrelated to the specific problem in the post (if so, feel free to tell me to open a new issue), but we're having an issue with buildkit caching in our Monorepo.

I started the discussion here: https://github.com/dagger/dagger/discussions/8604

Going down the path of setting a `+ignore` directive, I was able to reduce the required upload/cache size a bit, but in our Monorepo it's still massive (70+ GB). In my testing repo, using the same module I can see that my dagger call creates a bunch of snapshots, many of which have files that should be ignored:

<img width="894" alt="image" src="https://github.com/user-attachments/assets/4364a194-17b6-445d-9210-b38c22db9c7c">

My hunch is that this has something to do with Buildkit caching, maybe this specifically: https://github.com/dagger/dagger/blob/main/engine/buildkit/filesync.go#L73-L83

My questions are:
1. Why so many snapshots for a single run?
2. Why do several contain files I've explicitly ignored?

**Comment by shykes** [comment]
I believe this is fixed? @marcosnils @helderco

**Comment by helderco** [comment]
I don't think so. Even though it has improved we still don't ignore things like `node_modules` and `.venv` by default as explained above in https://github.com/dagger/dagger/issues/8499#issuecomment-2364170118.

**Comment by sipsma** [comment]
We've made a number of improvements in this area, including the aforementioned honor of `.gitignore` by default and most recently [this fix for modules](https://github.com/dagger/dagger/pull/11799).

I'm gonna close this issue for now since users who hit performance problems with this previously report it's no longer an issue. If any performance issues in monorepos come up again please open a new issue so we can tackle it in a more targeted way.
